version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${DBDATABASE}
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
    ports:
      - "${DBPORT}:3306"
    volumes:
      - db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local